name = "GliderAnalysis"
uuid = "e51f8d11-3fc3-46ad-ab4b-d2d7db6d6da8"
authors = ["dankelley <kelley.dan@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
